# Generated by Django 3.0.5 on 2020-04-26 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=256)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('message', models.CharField(max_length=5000)),
                ('invitee_emails', models.CharField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('create_event_user', models.ForeignKey(default=99999999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
